### ISSUE TITLE
Dimension mismatch

### ISSUE THREAD

**Issue by kakaisi** [Zhaocy-Research/TransformerST#4]
Dear professor！
When I run the co-representation of image and expression data according to your guidance, there is a dimension mismatch problem, I don't know how to solve it, can you help me? Looking forward to your reply. Thank you very much！

D:\Anaconda3\envs\TransformerST\python.exe "D:\Pycharm Project\TransformerST\Mouse_Lung_histology.py" 
===== Using device: cuda:0
===== Project 1 : 151507
adata: (4226, 33538)
===== Preprocessing Data 
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Anaconda3\envs\TransformerST\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
==== Graph Construction Finished
Using gene expression data without vision transformer processing.
z_flattened shape: torch.Size([8452, 64])
self.embedding.weight.t() shape: torch.Size([64, 128])
Traceback (most recent call last):
  File "D:\Pycharm Project\TransformerST\Mouse_Lung_histology.py", line 206, in <module>
    TransformerST_net.train_with_dec()
  File "D:\Pycharm Project\TransformerST\src\TransformerST_train_adaptive.py", line 173, in train_with_dec
    self.train_without_dec()
  File "D:\Pycharm Project\TransformerST\src\TransformerST_train_adaptive.py", line 130, in train_without_dec
    latent_z, de_feat, _, feat_x = self.model(self.node_X, self.adj_norm,self.adj_norm_prue,training)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pycharm Project\TransformerST\src\TransformerST_model.py", line 561, in forward
    de_feat = self.decoder(z)
              ^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\TransformerST\Lib\site-packages\torch\nn\modules\linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4226x192 and 128x3000)

**Comment by Mengflz** [comment]
Hi, I got the same issue. Have you solved this problem?

**Comment by cjhong** [comment]
Hi,

This is a great work! but I hope Zhao provides us 1 or 2 concrete example code. 

I attempted to run "Vision Transformer" part first.

I downloaded the mice Lung.zip data and properly configured all paths associated with the dataset in the codes and then ran 'python3 main.py' under the subfolder ('Vision Transformer').

I got the same error message

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3691x49152 and 37632x1024)
